package com.gondev.domain.model

data class MovieDetailModel(
    override val backdropPath: String?,
    override val id: Int,
    override val originalLanguage: String,
    override val overview: String,
    override val popularity: Double,
    override val posterPath: String?,
    override val title: String,
    override val releaseDate: String,
    override val genres: List<Genre>,
    override val homepage: String?,
    override val productionCompanies: List<ProductionCompany>,
    override val productionCountries: List<ProductionCountry>,
    override val spokenLanguages: List<SpokenLanguage>,
    override val status: String,
    override val tagline: String?,
    override val videos: List<Video>,
    override val adult: Boolean,
    override val originalTitle: String,
    override val voteAverage: Double,
    override val voteCount: Int,
    val belongsToCollection: String?,
    val budget: Long,
    val imdbId: String?,
    val revenue: Long,
    val runtime: Int?,
): IMovieModel, IMedialDetail
